// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJIZPpPNh-kovtv7DL_BP7lRPpqqmb0vg',
    appId: '1:1006207861742:web:f740c61f01b2bfa09c84ff',
    messagingSenderId: '1006207861742',
    projectId: 'revive-ad075',
    authDomain: 'revive-ad075.firebaseapp.com',
    storageBucket: 'revive-ad075.firebasestorage.app',
    measurementId: 'G-0EJJXFTBRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmGxt0v96oW2tam8me2ukO4pCgmThwQ18',
    appId: '1:1006207861742:android:1630a71dd4909c759c84ff',
    messagingSenderId: '1006207861742',
    projectId: 'revive-ad075',
    storageBucket: 'revive-ad075.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoYzcN3P734bDuy7SqEasBWq5XDsi-c5s',
    appId: '1:1006207861742:ios:14791458522fbd439c84ff',
    messagingSenderId: '1006207861742',
    projectId: 'revive-ad075',
    storageBucket: 'revive-ad075.firebasestorage.app',
    iosBundleId: 'com.example.revive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoYzcN3P734bDuy7SqEasBWq5XDsi-c5s',
    appId: '1:1006207861742:ios:14791458522fbd439c84ff',
    messagingSenderId: '1006207861742',
    projectId: 'revive-ad075',
    storageBucket: 'revive-ad075.firebasestorage.app',
    iosBundleId: 'com.example.revive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJIZPpPNh-kovtv7DL_BP7lRPpqqmb0vg',
    appId: '1:1006207861742:web:078fccb6bad129bd9c84ff',
    messagingSenderId: '1006207861742',
    projectId: 'revive-ad075',
    authDomain: 'revive-ad075.firebaseapp.com',
    storageBucket: 'revive-ad075.firebasestorage.app',
    measurementId: 'G-D338QCW3F5',
  );
}
